config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "pages#homepage"
  get "about", to: "pages#about"

  resources :articles
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: {minimum: 3, maximum:50 }
    validates :description, presence: true, length: {minimum: 3, maximum:50 }




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]

    def index
        @all_articles = Article.all

    end

    def new
        @article = Article.new
    end

    def edit

    end

    def destroy
        @article.destroy

        flash[:notice] = "Article is deleted"
        redirect_to articles_path
    end

    def update
        if @article.update(article_params)
            flash[:notice] = "Article was successfully updated"
            redirect_to article_path(@article)

        else
            render :edit, status: :unprocessable_entity

        end

    end

    def create
        @article = Article.new(article_params)
        if @article.save
            flash[:notice] = 'Article was successfully created'
            redirect_to article_path(@article)
        else
            render :new, status: :unprocessable_entity
        end
        
    end

    def show
    end

    private
        def set_article
            @article = Article.find(params[:id])
        end

        def article_params
            params.require(:article).permit(:title, :description)

        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def homepage

    end

    def about

    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
    <h1>Following Errors could not get the article created</h1>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li> <%= msg %> </li>
        <% end %>
    </ul>
<% end %>

<%= form_for @article do |f| %>
<p>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
</p>
<p>
    <%= f.label :description %> <br>
    <%= f.text_area :description %>
</p>

<p>
    <%= f.submit %>
</p>

<% end %>

<%= link_to 'Back to listing page', articles_path %>

app/views/articles/destroy.html.erb
<h1> Delete Article </h1>

<% if @article.errors.any? %>
    <h1>Following Errors could not get the article Deleted</h1>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li> <%= msg %> </li>
        <% end %>
    </ul>
<% end %>

<%= form_for @article do |f| %>
<p>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
</p>
<p>
    <%= f.label :description %> <br>
    <%= f.text_area :description %>
</p>

<p>
    <%= f.submit %>
</p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>
<%= link_to 'Home page', root_path%><br>

<p><%= link_to 'Create New Article', new_article_path %></p>


<table>
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Edit</th>
        <th>Show</th> 
        <th>Delete</th> 
    </tr>

    <% @all_articles.each do |article| %>
    <tr>
        <td> <%= article.title %> </td>
        <td> <%= article.description %> </td>
        <td> <%= link_to 'Edit', edit_article_path(article.id) %></td>
        <td> <%= link_to 'Show', article_path(article.id) %></td>
        <td> <%= link_to 'Delete', article_path(article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>

    </tr>
    <% end%>
</table>

app/views/articles/new.html.erb
<h1> New Article </h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing Selected Article</h1>
<p>Title:  <%= @article.title%> </p>

<p>Description: <%= @article.description %> </p>

<%= link_to 'Edit this Article', edit_article_path(@article) %> |
<%= link_to 'Back to listing page', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, msg|%>
      <ul>
        <li> <%= msg %> </li>
      </ul>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>about page </h1>

<%= link_to 'HomePage', root_path %>

app/views/pages/homepage.html.erb
<h1> This is home page </h1>

<%= link_to 'Alpha blog', articles_path%> | <%= link_to 'About', about_path%>